routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Notification;
use App\Notifications\BlogPublishing;
use App\User;
Use App\Post;

/*Route::get('/test-mail', function (){
    $testEmail = '';
    $posts = Post::all();
    $publishing = true;

    Notification::route('mail', $testEmail)->notify(new BlogPublishing($posts, false));
    return 'Sent';
});*/


Route::get('/', 'PublicController@index')->name('index');
Route::get('post/{id}', 'PublicController@singlePost')->name('singlePost');
Route::get('order-summary/{id}', 'PublicController@orderSummary')->name('order-summary');
Route::get('about', 'PublicController@about')->name('about');
Route::get('contact', 'PublicController@contact')->name('contact');
Route::post('contact', 'PublicController@contactPost')->name('contactPost');
Route::get('profile', 'PublicController@profile')->name('profile')->middleware('verified');
Route::get('usps', 'PublicController@testUsps');
Auth::routes(['verify' => true]);

Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('/signupconfirmation', 'HomeController@signupConfirmation')->name('signupConfirmation');

Route::prefix('editor')->group(function(){
    Route::get('submitted-posts','AuthorController@submittedPosts')->name('editor.Posts');
}); 

Route::prefix('contributer')->group(function(){
    Route::get('/dashboard','AuthorController@dashboard')->name('cont.Dashboard');
    Route::get('posts','AuthorController@posts')->name('cont.Posts');
    Route::get('post/{id}','AuthorController@getPost')->name('cont.SinglePost');
    Route::get('preview-post/{id}','AuthorController@previewPost')->name('cont.PreviewPost');
    Route::get('createPost','AuthorController@createPost')->name('cont.CreatePost');
    Route::get('comments','AuthorController@comments')->name('cont.Comments');
    Route::post('delete-post/{id}','AuthorController@deletePost')->name('cont.deletePost');
    Route::post('updatePost/{id}', 'AuthorController@updatePost')->name('cont.UpdatePost');
});

Route::prefix('admin')->group(function(){
    Route::get('/dashboard', 'AdminController@dashboard')->name('adminDashboard');

    #content
    Route::get('posts', 'AdminController@posts')->name('admin.posts');
    Route::get('comments', 'AdminController@comments')->name('adminComments');
    Route::get('users', 'AdminController@users')->name('adminUsers');
    
    #Products
    Route::get('products', 'AdminController@products')->name('adminProducts');
    Route::post('product/{id}/delete', 'AdminController@deleteProduct')->name('adminDeleteProduct');
    Route::get('products/new', 'AdminController@newProduct')->name('adminNewProduct');
    Route::post('products/new', 'AdminController@newProductPost')->name('adminNewProduct');
    Route::get('product/{id}', 'AdminController@editProduct')->name('adminEditProduct');
    Route::post('product/{id}', 'AdminController@editProductPost')->name('adminEditProduct');
    Route::post('order/{id}', 'AdminController@editOrder')->name('admin.editOrder');
    Route::get('awaiting-shipment', 'AdminController@awaitingShipment')->name('admin.awaitingShipment');
});

Route::prefix('shop')->group(function() {
    Route::get('/', 'ShopController@index')->name('shop.index');
    Route::get('product/{slug}', 'ShopController@singleProduct')->name('shop.singleProduct');


    Route::get('checkout','ShopController@getCheckout')->name('shop.getCheckout');
    Route::get('paypalCheckout', 'ShopController@getPaypal')->name('shop.getPaypal');
    
    Route::post('process-payment', 'ShopController@processPayment')->name('shop.processPayment');
    Route::get('process-paypal', 'ShopController@processPaypal')->name('shop.processPaypal');

    Route::post('paypal', 'ShopController@paypal')->name('shop.paypal');

    Route::get('confirmation',  'ShopController@confirmation')->name('shop.orderConfirmation');

    //product
    Route::get('addToCart/{id}', 'ProductController@addToCart')->name('shop.addToCart');
    Route::get('shopping-cart','ProductController@getCart')->name('shop.cart');
    Route::get('reduceCart/{id}','ProductController@reduceItemInCart')->name('shop.reduceCart');
    Route::get('removeFromCart/{id}','ProductController@removeFromCart')->name('shop.removeFromCart');
});

Route::prefix('blog')->group(function(){
    Route::get('/', 'BlogController@index')->name('blog.index');
    Route::get('post/{slug}', 'BlogController@singlePost')->name('blog.singlePost');
});


Route::prefix('shipping')->group(function() {
    Route::post('cost', 'ShippingController@shippingCost')->name('shipping.cost');
    Route::post('lookup', 'ShippingController@lookup')->name('shipping.lookup');
    Route::post('tracking', 'ShippingController@tracking')->name('shipping.tracking');
    //Route::post('confirm', 'ShippingController@confirm')->name('shipping.confirm');
    Route::post('tax', 'ShippingController@taxRate')->name('shipping.tax');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Post extends Model
{
    protected $fillable = [
        'title', 'subtitle', 'header_image',
        'user_id', 'content', 'status',
        'notify_on_publish', 'publish_on',
        'unpublish_on', 'notification_sent', 'slug', 'published'
    ];

    protected $casts = [
        'notify_on_publish' => 'boolean',
        'notification_sent' => 'boolean',
        'published' => 'boolean'
    ];


    public function setPublishOnAttribute($value) {
        if($value == null)
            return;

        $value = Carbon::parse($value);
        $date = Carbon::createFromFormat('Y-m-d H:i:s', $value, 
            'America/Los_Angeles');
        $date->setTimezone('UTC');
        $this->attributes['publish_on'] = $date;
    }
    
    public function setUnpublishOnAttribute($value) {
        if($value == null)
            return;

        $value = Carbon::parse($value);
        $date = Carbon::createFromFormat('Y-m-d H:i:s', $value, 
            'America/Los_Angeles');
        $date->setTimezone('UTC');
        $this->attributes['unpublish_on'] = $date;
    }


    public function getPublishOnAttribute($value) {
        if($value == null)
            return $value;

        $date = Carbon::createFromFormat('Y-m-d H:i:s', $value);
        return $date;
    }

    public function getUnpublishOnAttribute($value) {
        if($value == null)
            return $value;

        $date = Carbon::createFromFormat('Y-m-d H:i:s', $value);
        return $date;
    }

    public function localPublishTime() {
        if($this->publish_on == null)
            return null;

        $date = Carbon::createFromFormat('Y-m-d H:i:s', $this->publish_on);
        $date->setTimezone('America/Los_Angeles');
        return $date;
    }

    public function localUnpublishTime() {
        if($this->unpublish_on == null)
            return null;

        $date = Carbon::createFromFormat('Y-m-d H:i:s', $this->unpublish_on);
        $date->setTimezone('America/Los_Angeles');
        return $date;
    }

    public function styledLocalPublishTime() {
        if($this->publish_on == null)
            return null;

        $date = Carbon::createFromFormat('Y-m-d H:i:s', $this->publish_on);
        $date->setTimezone('America/Los_Angeles');
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('m.d.Y'); 
    }


    public function setNotifyOnPublishAttribute($value) {
        $this->attributes['notify_on_publish'] = 
            (int)filter_var($value, FILTER_VALIDATE_BOOLEAN);
    }

    public function setNotificationSentAttribute($value) {
        $this->attribute['notification_sent'] = 
            (int)filter_var($value, FILTER_VALIDATE_BOOLEAN);
    }

    public function getCreatedAtAttribute($date) {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('m.d.Y');
    }

    public function getUpdatedAtAttribute($date) {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('Y-m-d');
    }

    public function user() {
        return $this->belongsTo('App\User');
    }

    public function views() {
        return $this->hasMany('App\PostView');
    }

}

resources/views/admin/awaitingShipment.blade.php
@extends('layouts.admin')

@section('title')
Matrilineal Nerd - Awaiting Shipment
@endsection

@section('content')
<div class="container text-center" style="margin-top:70px;">
        <h1 class="emphasis">Awaiting Shipment</h1>
        <hr />
        @if(count($orders) > 0)
            <h3 class="informative-header">Here is a list of orders currently awaiting shipment</h3>
        @else
            <h3 class="informative-header">There are currently no orders awaiting shipment</h3>
        @endif
        <br>
            @foreach($orders as $order)
            <div class="informative" style="margin-bottom: 35px;">
                <a href="{{route('order-summary', $order->id)}}" style="color:black !important;">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col emphasis">
                                    <h5>Order# {{$order->id}}</h5>
                                </div>

                                <div class="col informative text-center">
                                    @php
                                    $total = $order->post_price + $order->tax + $order->shipping;
                                    @endphp
                                    <span>Total Price ${{number_format($total, 2)}}</span>
                                </div>
                                <div class="col informative text-right">
                                    <small>Ordered on {{$order->created_at}}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            @endforeach
    </div>
@endsection

resources/views/admin/dashboard.blade.php
@extends('layouts.admin')

@section('title')
Matrilineal Nerd - Admin
@endsection

@section('content')
<div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-3">
                        <div class="card p-4">
                            <div class="card-body d-flex justify-content-between align-items-center">
                                <div>
                                    <span class="h4 d-block font-weight-normal mb-2">54</span>
                                    <span class="font-weight-light">Total Users</span>
                                </div>

                                <div class="h2 text-muted">
                                    <i class="icon icon-people"></i>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="card p-4">
                            <div class="card-body d-flex justify-content-between align-items-center">
                                <div>
                                    <span class="h4 d-block font-weight-normal mb-2">$32,400</span>
                                    <span class="font-weight-light">Income</span>
                                </div>

                                <div class="h2 text-muted">
                                    <i class="icon icon-wallet"></i>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="card p-4">
                            <div class="card-body d-flex justify-content-between align-items-center">
                                <div>
                                    <span class="h4 d-block font-weight-normal mb-2">900</span>
                                    <span class="font-weight-light">Downloads</span>
                                </div>

                                <div class="h2 text-muted">
                                    <i class="icon icon-cloud-download"></i>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="card p-4">
                            <div class="card-body d-flex justify-content-between align-items-center">
                                <div>
                                    <span class="h4 d-block font-weight-normal mb-2">32s</span>
                                    <span class="font-weight-light">Time</span>
                                </div>

                                <div class="h2 text-muted">
                                    <i class="icon icon-clock"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row ">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                Total Users
                            </div>

                            <div class="card-body p-0">
                                <div class="p-4">
                                    <canvas id="line-chart" width="100%" height="20"></canvas>
                                </div>

                                <div class="justify-content-around mt-4 p-4 bg-light d-flex border-top d-md-down-none">
                                    <div class="text-center">
                                        <div class="text-muted small">Total Traffic</div>
                                        <div>12,457 Users (40%)</div>
                                    </div>

                                    <div class="text-center">
                                        <div class="text-muted small">Banned Users</div>
                                        <div>95,333 Users (5%)</div>
                                    </div>

                                    <div class="text-center">
                                        <div class="text-muted small">Page Views</div>
                                        <div>957,565 Pages (50%)</div>
                                    </div>

                                    <div class="text-center">
                                        <div class="text-muted small">Total Downloads</div>
                                        <div>957,565 Files (100 TB)</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/admin/editProduct.blade.php
@extends('layouts.admin')

@section('title')
Matrilineal Nerd - Edit Product
@endsection

@section('content')
<script src="https://cdn.ckeditor.com/4.13.0/standard/ckeditor.js"></script>
<div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header bg-light">
                                Edit Product
                            </div>
                            @if(Session::has('success'))
                                <div class="alert alert-success">{{Session::get('success')}}</div>
                            @endif

                            @if($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach($errors->all() as $error)
                                    <li>{{$error}}</li>
                                    @endforeach
                                </ul>
                            </div>
                            @endif
                            <form
                                action="{{ route('adminEditProduct', $product->id) }}"
                                method="POST"
                                enctype="multipart/form-data"
                            >
                            @csrf
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-8">
                                            <div class="form-group">
                                                <label
                                                    for="normal-input"
                                                    class="form-control-label"
                                                    >Thumbnail</label
                                                >
                                                <input
                                                    type="file"
                                                    name="thumbnail"
                                                    id="normal-input"
                                                    class="form-control"
                                                    value="Input value"
                                                    placeholder="Add a thumbnail (optional)"
                                                />
                                                <img src="{{asset($product->image)}}" width=100 alt="" style="margin-top:25px;">
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Name -->
                                    <div class="row">
                                        <div class="col-md-8">
                                            <div class="form-group">
                                                <label
                                                    for="normal-input"
                                                    class="form-control-label"
                                                    >Product Name</label
                                                >
                                                <input
                                                    name="title"
                                                    type="text"
                                                    id="normal-input"
                                                    class="form-control"
                                                    value="{{$product->title}}"/>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- CATEGORY -->
                                    <div class="row">
                                        <div class="col-md-8">
                                            <div class="form-group">
                                                <label
                                                    for="normal-input"
                                                    class="form-control-label"
                                                    >Product Category</label
                                                >
                                                <div>
                                                <select name="category" id="category">
                                                    @foreach($categories as $category)
                                                        @php
                                                        $result = $product->category == $category;
                                                        @endphp
                                                        <option value="{{$category}}" {{$product->category==$category ? 'selected' : ''}}>
                                                            {{$category}}
                                                        </option>
                                                    @endforeach
                                                </select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Product Weight-->
                                    <div class="row" style="margin-top:20px;">
                                        <div class="col-md-8">
                                            <div class="form-group">
                                                <label
                                                    for="normal-input"
                                                    class="form-control-label"
                                                    >Product Weight</label
                                                >
                                                <div class="row">
                                                    <div class="col">
                                                        <label
                                                        for="normal-input"
                                                        class="form-control-label"
                                                        >
                                                            <small>Pound(s)</small>
                                                        </label
                                                        >
                                                        <input
                                                        name="pounds"
                                                        type="number"
                                                        step="1"
                                                        min="0"
                                                        id="normal-input"
                                                        class="form-control"
                                                        value="{{$product->pounds}}"/>
                                                    </div>

                                                    <div class="col">
                                                        <label
                                                        for="normal-input"
                                                        class="form-control-label"
                                                        >
                                                            <small>Ounce(s)</small>
                                                        </label
                                                        >
                                                        <input
                                                        name="ounces"
                                                        type="number"
                                                        step=".01"
                                                        min="0"
                                                        id="normal-input"
                                                        class="form-control"
                                                        value="{{$product->ounces}}"/>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                    <!-- DESCRIPTION -->
                                    <div class="row mt-4">
                                        <div class="col-md-8">
                                            <div class="form-group">
                                                <label
                                                    for="placeholder-input"
                                                    class="form-control-label"
                                                    >Description</label
                                                >
                                                <textarea name="editor1" id="content" rows="5">{{$product->description}}</textarea>
                                                <script>
                                                CKEDITOR.replace('editor1');
                                                </script>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- PRICE -->
                                    <div class="row">
                                        <div class="col-md-8">
                                            <div class="form-group">
                                                <label
                                                    for="normal-input"
                                                    class="form-control-label"
                                                    >Price</label
                                                >
                                                <input
                                                    name="price"
                                                    type="number"
                                                    step=".01"
                                                    id=""
                                                    min="0"
                                                    class="form-control"
                                                    value={{$product->price}}
                                                />
                                            </div>
                                        </div>
                                    </div>
                                    <button
                                        class="btn btn-success"
                                        type="submit"
                                    >
                                        Update Product
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/admin/products.blade.php
@extends('layouts.admin')
@section('title')
Matrilineal Nerd - Products
@endsection


@section('content')
<div class="content">
    <div class="card">
        <div class="card-header bg-light">
            <b>Products</b>

            <a href="{{ route('adminNewProduct')}}" class="btn btn-primary btn-sm">New Product</a>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Thumbnail</th>
                            <th>Price</th>
                            <th>Description</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($products as $product)
                        <tr>
                            <td>{{$product->id}}</td>
                            <td class="text-nowrap"><a
                                    href="{{route('shop.singleProduct', $product->slug) }}">{{$product->title}}</td>
                            <td><img src="{{asset($product->image)}}" width=100 alt=""></td>
                            <td>${{$product->price}}</td>
                            <td>{{$product->description}}</td>
                            <!---<td>{{ \Carbon\Carbon::parse($product->created_at)->diffForHumans() }}</td>
                                        <td>{{ \Carbon\Carbon::parse($product->updated_at)->diffForHumans() }}</td>-->
                            <td>
                                <a href="{{ route('adminEditProduct', $product->id) }}" class="btn-warning">
                                    <i class="icon icon-pencil"></i></a>
                                <form method="POST" id="deleteProduct-{{ $product->id}}"
                                    action="{{route('adminDeleteProduct', $product->id)}}">@csrf
                                    <button type="button" class="btn btn-danger" data-toggle="modal"
                                        data-target="#deleteProductModal-{{$product->id}}">
                                        x
                                    </button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                </table>
            </div>
        </div>
    </div>
</div>

<!--Modal -->
@foreach($products as $product)
<div class="modal fade" id="deleteProductModal-{{$product->id}}" tabindex="-1" role="dialog"
    aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-danger border-0">
                <h5 class="modal-title text-white">You are about to delete {{$product->title}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body p-5">
                Are you sure?
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">No, Keep it</button>
                <form method="POST" id="deleteProduct-{{$product->id}}"
                    action="{{route('adminDeleteProduct', $product->id)}}">
                    @csrf
                    <button type="submit" class="btn btn-primary">Yes, Delete it</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endforeach
@endsection